### ISSUE TITLE
tldextract cache error on mac

### ISSUE THREAD

**Issue by aschulm** [ucsdsysnet/trufflehunter#2]
`unable to cache TLDs in file /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tldextract/.tld_set: [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tldextract/.tld_set'`

looks like it's trying to cache the tld set in a file on first use of the package, but that file is in a root folder. can we disable tld caching?

**Comment by alexliu0809** [comment]
Fixed in this [commit](https://github.com/ucsdsysnet/trufflehunter/commit/e3890999c8e46eb0de27108dcb30dec8c1c943a5)
